pub struct DescStrings {
    pub idle: &'static str,
    pub module_singular: &'static str,
    pub module_plural: &'static str,
    pub font_prefix: &'static str,
}

pub fn desc_strings(lang: &str) -> DescStrings {
    match lang {
        "zh-CN" => DescStrings { idle: "空闲 — 未加载模块", module_singular: "模块", module_plural: "模块", font_prefix: "字体" },
        "zh-TW" => DescStrings { idle: "閒置 — 未載入模組", module_singular: "模組", module_plural: "模組", font_prefix: "字體" },
        "ja" => DescStrings { idle: "アイドル — モジュール未ロード", module_singular: "モジュール", module_plural: "モジュール", font_prefix: "フォント" },
        "ko" => DescStrings { idle: "유휴 — 모듈 미로드", module_singular: "모듈", module_plural: "모듈", font_prefix: "글꼴" },
        "ru" => DescStrings { idle: "Ожидание — Модули не загружены", module_singular: "Модуль", module_plural: "Модулей", font_prefix: "Шрифт" },
        "es" => DescStrings { idle: "Inactivo — Sin módulos cargados", module_singular: "Módulo", module_plural: "Módulos", font_prefix: "Fuente" },
        "fr" => DescStrings { idle: "Inactif — Aucun module chargé", module_singular: "Module", module_plural: "Modules", font_prefix: "Police" },
        "de" => DescStrings { idle: "Leerlauf — Keine Module geladen", module_singular: "Modul", module_plural: "Module", font_prefix: "Schrift" },
        "pt-BR" => DescStrings { idle: "Inativo — Nenhum módulo carregado", module_singular: "Módulo", module_plural: "Módulos", font_prefix: "Fonte" },
        "tr" => DescStrings { idle: "Boşta — Yüklü modül yok", module_singular: "Modül", module_plural: "Modül", font_prefix: "Yazı Tipi" },
        "ar" => DescStrings { idle: "خامل — لا توجد وحدات محمّلة", module_singular: "وحدة", module_plural: "وحدات", font_prefix: "خط" },
        "vi" => DescStrings { idle: "Chờ — Không có module nào được tải", module_singular: "Module", module_plural: "Module", font_prefix: "Phông" },
        "uk" => DescStrings { idle: "Очікування — Модулі не завантажені", module_singular: "Модуль", module_plural: "Модулів", font_prefix: "Шрифт" },
        "it" => DescStrings { idle: "Inattivo — Nessun modulo caricato", module_singular: "Modulo", module_plural: "Moduli", font_prefix: "Font" },
        "id" => DescStrings { idle: "Menganggur — Tidak ada modul dimuat", module_singular: "Modul", module_plural: "Modul", font_prefix: "Font" },
        "pl" => DescStrings { idle: "Bezczynny — Brak załadowanych modułów", module_singular: "Moduł", module_plural: "Modułów", font_prefix: "Czcionka" },
        "th" => DescStrings { idle: "ว่าง — ไม่มีโมดูลที่โหลด", module_singular: "โมดูล", module_plural: "โมดูล", font_prefix: "ฟอนต์" },
        "hi" => DescStrings { idle: "निष्क्रिय — कोई मॉड्यूल लोड नहीं", module_singular: "मॉड्यूल", module_plural: "मॉड्यूल", font_prefix: "फ़ॉन्ट" },
        "bn" => DescStrings { idle: "নিষ্ক্রিয় — কোনো মডিউল লোড হয়নি", module_singular: "মডিউল", module_plural: "মডিউল", font_prefix: "ফন্ট" },
        "nl" => DescStrings { idle: "Inactief — Geen modules geladen", module_singular: "Module", module_plural: "Modules", font_prefix: "Lettertype" },
        "sv" => DescStrings { idle: "Inaktiv — Inga moduler laddade", module_singular: "Modul", module_plural: "Moduler", font_prefix: "Typsnitt" },
        "da" => DescStrings { idle: "Inaktiv — Ingen moduler indlæst", module_singular: "Modul", module_plural: "Moduler", font_prefix: "Skrifttype" },
        "fi" => DescStrings { idle: "Odottaa — Ei ladattuja moduuleja", module_singular: "Moduuli", module_plural: "Moduulia", font_prefix: "Fontti" },
        "no" => DescStrings { idle: "Inaktiv — Ingen moduler lastet", module_singular: "Modul", module_plural: "Moduler", font_prefix: "Skrifttype" },
        "cs" => DescStrings { idle: "Nečinný — Žádné načtené moduly", module_singular: "Modul", module_plural: "Modulů", font_prefix: "Písmo" },
        "el" => DescStrings { idle: "Αδρανές — Κανένα module φορτωμένο", module_singular: "Module", module_plural: "Modules", font_prefix: "Γραμματοσειρά" },
        "hu" => DescStrings { idle: "Tétlen — Nincs betöltött modul", module_singular: "Modul", module_plural: "Modul", font_prefix: "Betűtípus" },
        "ro" => DescStrings { idle: "Inactiv — Niciun modul încărcat", module_singular: "Modul", module_plural: "Module", font_prefix: "Font" },
        "bg" => DescStrings { idle: "Неактивен — Няма заредени модули", module_singular: "Модул", module_plural: "Модула", font_prefix: "Шрифт" },
        "sr" => DescStrings { idle: "Неактиван — Нема учитаних модула", module_singular: "Модул", module_plural: "Модула", font_prefix: "Фонт" },
        "ca" => DescStrings { idle: "Inactiu — Cap mòdul carregat", module_singular: "Mòdul", module_plural: "Mòduls", font_prefix: "Font" },
        "fa" => DescStrings { idle: "بیکار — هیچ ماژولی بارگذاری نشده", module_singular: "ماژول", module_plural: "ماژول", font_prefix: "فونت" },
        "he" => DescStrings { idle: "לא פעיל — אין מודולים טעונים", module_singular: "מודול", module_plural: "מודולים", font_prefix: "גופן" },
        "af" => DescStrings { idle: "Ledig — Geen modules gelaai", module_singular: "Module", module_plural: "Modules", font_prefix: "Lettertipe" },
        "pt-PT" => DescStrings { idle: "Inativo — Nenhum módulo carregado", module_singular: "Módulo", module_plural: "Módulos", font_prefix: "Tipo de letra" },
        _ => DescStrings { idle: "Idle — No Module Mounted", module_singular: "Module", module_plural: "Modules", font_prefix: "Font" },
    }
}
